### ISSUE TITLE
DatabaseLockError: Unable to get write lock on /.../xapian_index: already locked

### ISSUE THREAD

**Issue by camilonova** [django-haystack/celery-haystack#55]
Hi, I'm getting a bunch of this:

```
[2016-02-23 15:10:08,177: INFO/MainProcess] Received task: celery_haystack.tasks.CeleryHaystackSignalHandler[d7321172-d822-4544-b7c8-67126842a951]
[2016-02-23 15:10:08,182: ERROR/Worker-3] celery_haystack.tasks.CeleryHaystackSignalHandler[ed1401c4-0aa4-4c87-bd8c-916cc9905433]: Unable to get write lock on /.../xapian_index: already locked
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery_haystack/tasks.py", line 123, in run
    current_index.update_object(instance, using=using)
  File "/usr/local/lib/python2.7/dist-packages/haystack/indexes.py", line 282, in update_object
    backend.update(self, [instance])
  File "/usr/local/lib/python2.7/dist-packages/xapian_backend.py", line 276, in update
    database = self._database(writable=True)
  File "/usr/local/lib/python2.7/dist-packages/xapian_backend.py", line 1131, in _database
    database = xapian.WritableDatabase(self.path, xapian.DB_CREATE_OR_OPEN)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 4304, in __init__
    _xapian.WritableDatabase_swiginit(self,_xapian.new_WritableDatabase(*args))
DatabaseLockError: Unable to get write lock on /.../xapian_index: already locked
```

Seems reasonable that if my celery setup uses multiple workers they will try to use different tasks at the same time to change the folder, if so, can we set the celery task to be executed by one at a time?

Or, can you tell how can I fix it?

**Comment by camilonova** [comment]
It was better to stop using xapian at all.

**Comment by karolyi** [comment]
Could you please elaborate? I'm getting the same error when trying to write the db with multiprocessed haystack (workers).

**Comment by bigjust** [comment]
I would suggest running at most one worker for the queue responsible for updating xapian.
